import man from '../images/man.png';

const organizers = [
    {
        name: "Roneel Valambhia",
        phone: "+91 94097 59776",
        image: "https://dsc-slop.github.io/images/team/Roneel.jpg",
        github: "https://github.com/RoneelV",
        linkedin: "#",
    },
    {
        name: "Prakhar Agarwal",
        phone: "+91 94622 00865",
        image: "https://dsc-slop.github.io/images/team/Prakhar.jpeg",
        github: "https://github.com/prakhartech",
        linkedin: "https://www.linkedin.com/in/prakhar-agrawal-0173b8175/",
    },
    {
        name: "Aniruddh Muley",
        phone: "+91 63560 34467",
        image: "https://dsc-slop.github.io/images/team/AniruddhMuley.png",
        github: "https://github.com/Aniruddhmuley2001",
        linkedin: "https://www.linkedin.com/in/aniruddh-muley-647884193",
    },
    {
        name: "Satyadev Patel",
        phone: "+91 81289 84425",
        image: "https://dsc-slop.github.io/images/team/SatyadevPatel.jpg",
        github: "https://github.com/Satyadev-Patel",
        linkedin: "https://www.linkedin.com/in/satyadev-patel-8ba65a1a7/",
    },
    {
        name: "Fenil Kamdar",
        phone: "+91 98252 06109",
        image: "https://dsc-slop.github.io/images/team/FenilKamdar.jpg",
        github: "https://github.com/fenu28",
        linkedin: "https://www.linkedin.com/in/fenil-kamdar/",
    },
    {
        name: "Miti Purohit",
        phone: "+91 91069 54865",
        image: "https://dsc-slop.github.io/images/team/MitiPurohit.jpeg",
        github: "https://github.com/miti2001",
        linkedin: "https://www.linkedin.com/in/miti-purohit-25aa391a8/",
    },
    {
        name: "Isha Kikani",
        phone: "+91 82389 25426",
        image: "https://dsc-slop.github.io/images/team/IshaKikani.jpg",
        github: "https://github.com/Ishakikani9117",
        linkedin: "https://www.linkedin.com/in/isha-kikani-1795271a9/",
    },
    {
        name: "Vrutik Prajapati",
        phone: "+91 70169 79017",
        image: "https://dsc-slop.github.io/images/team/VrutikPrajapati.jpg",
        github: "https://github.com/vrutik2809",
        linkedin: "https://www.linkedin.com/in/vrutik-prajapati/",
    },
    {
        name: "Harsh Metkel",
        phone: "+91 81286 62202",
        image: "https://dsc-slop.github.io/images/team/HarshMetkel.jpg",
        github: "https://github.com/harshmetkel24",
        linkedin: "https://www.linkedin.com/in/harshkumar-metkel-9a44731b6/",
    },
    {
        name: "Harsh Patel",
        phone: "+91 84697 72575",
        image: "https://dsc-slop.github.io/images/team/HarshPatel.jpeg",
        github: "https://github.com/harshpatel2910",
        linkedin: "https://www.linkedin.com/in/harsh-patel-413574203/",
    },
    {
        name: "Krupal Shah",
        phone: "+91 90333 51125",
        image: "https://dsc-slop.github.io/images/team/KrupalShah.jpeg",
        github: "https://github.com/shah-krupal",
        linkedin: "https://www.linkedin.com/in/krupal-shah-001379219/",
    },
    {
        name: "Chaitri Gudhka",
        phone: "+91 95128 51803",
        image: "https://dsc-slop.github.io/images/team/ChaitriGudhka.jpg",
        github: "#",
        linkedin: "https://www.linkedin.com/in/chaitri-gudhka-863444210",
    },
    {
        name: "Shivam Madlani",
        phone: "+91 94283 80079",
        image: "https://dsc-slop.github.io/images/team/ShivamMadlani.jpg",
        github: "https://github.com/ShivamMadlani",
        linkedin: "https://www.linkedin.com/in/shivam-madlani-6a2490226/",
    },
    {
        name: "Jay Malaviya",
        phone: "+91 87806 22867",
        image: "https://dsc-slop.github.io/images/team/JayMalavia.jpeg",
        github: "https://github.com/Jam-Burger",
        linkedin: "https://www.linkedin.com/in/jay-malaviya",
    },
    {
        name: "Nikita",
        phone: "+91 70160 41010",
        image: "https://dsc-slop.github.io/images/team/NikitaShah.jpeg",
        github: "https://github.com/Nikita-Shah7",
        linkedin: "#",
    },
];

export default organizers;