import man from '../images/man.png';

const organizers = [
    {
        name: "Vrutik Prajapati",
        phone: "+91 70169 79017",
        image: "https://dsc-slop.github.io/images/team/VrutikPrajapati.jpg",
        github: "https://github.com/vrutik2809",
        linkedin: "https://www.linkedin.com/in/vrutik-prajapati/",
    },
    {
        name: "Harsh Metkel",
        phone: "+91 81286 62202",
        image: "https://dsc-slop.github.io/images/team/HarshMetkel.jpg",
        github: "https://github.com/harshmetkel24",
        linkedin: "https://www.linkedin.com/in/harshkumar-metkel-9a44731b6/",
    },
    {
        name: "Harsh Patel",
        phone: "+91 84697 72575",
        image: "https://dsc-slop.github.io/images/team/HarshPatel.jpeg",
        github: "https://github.com/harshpatel2910",
        linkedin: "https://www.linkedin.com/in/harsh-patel-413574203/",
    },
    {
        name: "Krupal Shah",
        phone: "+91 90333 51125",
        image: "https://dsc-slop.github.io/images/team/KrupalShah.jpeg",
        github: "https://github.com/shah-krupal",
        linkedin: "https://www.linkedin.com/in/krupal-shah-001379219/",
    },
    {
        name: "Chaitri Gudhka",
        phone: "+91 95128 51803",
        image: "https://dsc-slop.github.io/images/team/ChaitriGudhka.jpg",
        github: "#",
        linkedin: "https://www.linkedin.com/in/chaitri-gudhka-863444210",
    },
    {
        name: "Shivam Madlani",
        phone: "+91 94283 80079",
        image: "https://dsc-slop.github.io/images/team/ShivamMadlani.jpg",
        github: "https://github.com/ShivamMadlani",
        linkedin: "https://www.linkedin.com/in/shivam-madlani-6a2490226/",
    },
    {
        name: "Jay Malaviya",
        phone: "+91 87806 22867",
        image: "https://dsc-slop.github.io/images/team/Jay.JPG",
        github: "https://github.com/Jam-Burger",
        linkedin: "https://www.linkedin.com/in/jay-malaviya",
    },
    {
        name: "Nikita Shah",
        phone: "+91 70160 41010",
        image: "https://dsc-slop.github.io/images/team/NikitaShah.jpg",
        github: "https://github.com/Nikita-Shah7",
        linkedin: "#",
    },
    {
        name: "Pranav Patel",
        phone: "+91 74878 95394",
        image: "https://dsc-slop.github.io/images/team/Pranav.jpg",
        github: "https://github.com/techman0256",
        linkedin: "#",
    },
    {
        name: "Bhavya Dudhagara",
        phone: "+91 88966 55557",
        image: "https://dsc-slop.github.io/images/team/Bhavya.jpg",
        github: "https://github.com/Bhavya2104",
        linkedin: "https://www.linkedin.com/in/bhavya-dudhagara-653006194/",
    },
    {
        name: "Aayush Patel",
        phone: "+91 98751 57558",
        image: "https://dsc-slop.github.io/images/team/Aayush.jpg",
        github: "https://github.com/Aayush121202",
        linkedin: "https://www.linkedin.com/in/aayush-patel-57284a220/",
    },
    {
        name: "Parth Vadodaria",
        phone: "+91 93131 38372",
        image: "https://dsc-slop.github.io/images/team/Parth.jpg",
        github: "https://github.com/Parth3105",
        linkedin: "https://www.linkedin.com/in/parth-vadodaria-8528b6254/",
    },
    {
        name: "Maulik Kansara",
        phone: "+91 96877 87304",
        image: "https://dsc-slop.github.io/images/team/Maulik.jpg",
        github: "https://github.com/maulikk04",
        linkedin: "https://www.linkedin.com/in/maulik-kansara-846060251/",
    },
    {
        name: "Vedant Trivedi",
        phone: "+91 94263 96758",
        image: "https://dsc-slop.github.io/images/team/Vedant.jpg",
        github: "https://github.com/Vedanttrivedi",
        linkedin: "https://www.linkedin.com/in/vedant-trivedi-95b7b2169/",
    },
    {
        name: "Dharmi Patel",
        phone: "+91 82383 15800",
        image: "https://dsc-slop.github.io/images/team/Dharmi.jpeg",
        github: "https://github.com/dharmi13",
        linkedin: "#",
    },
];

export default organizers;